# Generated by Django 4.1.7 on 2023-03-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomkey', models.CharField(max_length=255, unique=True)),
                ('userIds', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255)),
                ('PointsA', models.IntegerField(default=0)),
                ('PointsB', models.IntegerField(default=0)),
                ('PointsC', models.IntegerField(default=0)),
                ('PointsD', models.IntegerField(default=0)),
                ('Moves', models.CharField(max_length=255)),
                ('Turn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('roomtoken', models.CharField(max_length=255)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
    ]
