# Generated by Django 4.1.7 on 2023-03-30 10:35

import chat.gameRoomManager
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=chat.gameRoomManager.generate_room_id, max_length=6, unique=True)),
                ('moves', models.TextField(blank=True, null=True)),
                ('turn', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETE', 'Complete'), ('ACCEPTING', 'Accepting')], default='INACTIVE', max_length=10)),
                ('winnerList', models.TextField(blank=True, null=True)),
                ('looserList', models.TextField(blank=True, null=True)),
                ('game_state', models.JSONField(default=dict)),
                ('game_status', models.CharField(choices=[('BID_TYPE', 'bid_type'), ('BID_AMOUNT', 'bid_amount'), ('TICK', 'tick')], default='BID_TYPE', max_length=10)),
                ('round_player_index', models.PositiveIntegerField(default=0)),
                ('round_tick_index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_cards', models.JSONField(blank=True, null=True)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.gameroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user')),
            ],
        ),
        migrations.AddField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(through='chat.Player', to='chat.user'),
        ),
    ]
