# Generated by Django 4.1.7 on 2023-03-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='game_status',
            new_name='game_action',
        ),
        migrations.RenameField(
            model_name='gameroom',
            old_name='game_state',
            new_name='game_header',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='game_header_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
