# Generated by Django 4.1.7 on 2023-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10, unique=True)),
                ('player_one', models.CharField(max_length=100)),
                ('player_two', models.CharField(blank=True, max_length=100, null=True)),
                ('player_three', models.CharField(blank=True, max_length=100, null=True)),
                ('player_four', models.CharField(blank=True, max_length=100, null=True)),
                ('moves', models.TextField(blank=True, null=True)),
                ('turn', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
