# Generated by Django 4.1.7 on 2023-04-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestats',
            name='room_id',
            field=models.CharField(default='', max_length=6),
        ),
    ]
