# Generated by Django 4.1.7 on 2023-03-27 06:01

import chat.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_gameroom_delete_room'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gameroom',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='created_at',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='looserList',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player_four_leave_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player_one_leave_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player_three_leave_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player_two_leave_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='winnerList',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player_four',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player_one',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player_three',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player_two',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_id',
            field=models.CharField(default=chat.models.generate_room_id, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETE', 'Complete'), ('ACCEPTING', 'Accepting')], default='INACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='turn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
