# Generated by Django 4.1.7 on 2023-04-03 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_game_status_gameroom_game_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winOrLose', models.BooleanField(default=False)),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.gameroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user')),
            ],
        ),
    ]
