# Generated by Django 4.1.7 on 2023-04-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_gamestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestats',
            name='room_id',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
