# Generated by Django 4.1.7 on 2023-03-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_gameroom_managers_remove_gameroom_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gameroom',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player_four',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player_one',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player_three',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player_two',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='cards',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='cards_distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_cards', models.JSONField(blank=True, null=True)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.gameroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user')),
            ],
        ),
        migrations.AddField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(through='chat.Player', to='chat.user'),
        ),
    ]
