# Generated by Django 4.1.7 on 2023-03-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_gameroom_managers_remove_gameroom_player_four_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='player_four_leave_time',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player_one_leave_time',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player_three_leave_time',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='player_two_leave_time',
        ),
    ]
