# Generated by Django 4.1.7 on 2023-03-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='playercount',
            field=models.IntegerField(default=0),
        ),
    ]
