# Generated by Django 4.1.7 on 2023-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_gameroom_playercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
