# Generated by Django 4.1.7 on 2023-03-28 13:50

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_player_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_state',
            field=picklefield.fields.PickledObjectField(default=None, editable=False, null=True),
        ),
    ]
